Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -13,8 +13,16 @@ jobs:
           name: "Check PR Title"
           command: |
             #!/bin/bash
-            # Extract PR number from the CIRCLE_PULL_REQUEST URL
-            echo $CIRCLE_BRANCH
+            # Extract the branch name from the environment variable
+            BRANCH_NAME=$CIRCLE_BRANCH
+            
+            # Check if the branch name starts with the required pattern
+            if [[ $BRANCH_NAME =~ ^SCP-[0-9]{4} ]]; then
+              echo "Branch name '$BRANCH_NAME' is valid."
+            else
+              echo "Branch name '$BRANCH_NAME' is invalid. It must start with 'SCP-' followed by 4 digits."
+              exit 1
+            fi
             
 
 workflows:
